services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/certs:/etc/letsencrypt/live
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/letsencrypt-data:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    env_file:
      - .env
    command: /bin/sh -c "envsubst '\$DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt/live
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/letsencrypt-data:/data/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
            while :; do
              certbot renew --webroot -w /data/letsencrypt;
              sleep 12h & wait $${!};
            done"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
