# Generated by Django 5.2.4 on 2025-11-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def copy_writeups(apps, schema_editor):
    OldWriteup = apps.get_model('blog', 'Writeup')
    NewWriteup = apps.get_model('infosec', 'Writeup')
    for old in OldWriteup.objects.all():
        NewWriteup.objects.create(
            id=old.id,
            title=old.title,
            slug=old.slug,
            author_id=old.author_id,
            difficulty=old.difficulty,
            points=old.points,
            solver_count=old.solver_count,
            visibility=old.visibility,
            published_on=old.published_on,
            edited_on=old.edited_on,
            picture=old.picture,
            password=old.password,
            category_id=old.category_id,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0008_project_date_beginning_project_date_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CTF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("date_beginning", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
            ],
            options={
                "verbose_name": "CTF",
                "verbose_name_plural": "CTFs",
                "ordering": ["-date_beginning"],
            },
        ),
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Issuer",
                "verbose_name_plural": "Issuers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        help_text="the unique identifier for the CVE (e.g., CVE-2025-12345)",
                        max_length=20,
                        unique=True,
                        verbose_name="cve_id",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="a detailed description of the vulnerability",
                        verbose_name="description",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was published",
                        null=True,
                        verbose_name="published_date",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was last updated",
                        null=True,
                        verbose_name="last_modified_date",
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="the severity score of the vulnerability",
                        max_digits=3,
                        null=True,
                        verbose_name="cvss_score",
                    ),
                ),
                (
                    "vulnerable_product",
                    models.CharField(
                        blank=True,
                        help_text="the affected product(s)",
                        max_length=200,
                        null=True,
                        verbose_name="vulnerable_product",
                    ),
                ),
                (
                    "references_url",
                    models.URLField(
                        blank=True,
                        help_text="link to official references or advisories",
                        max_length=300,
                        null=True,
                        verbose_name="references_url",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cve",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField()),
                (
                    "certification_detail_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the official page of the certification",
                        null=True,
                        verbose_name="Certification URL",
                    ),
                ),
                (
                    "obtained_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the certification was obtained",
                        null=True,
                        verbose_name="Obtained Date",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification",
                        to="blog.article",
                        verbose_name="Related Article",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization or platform that issued the certification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="infosec.issuer",
                        verbose_name="Issuer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Writeup",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.post",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("insane", "Insane"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Score or point value for this challenge.",
                        verbose_name="Points",
                    ),
                ),
                (
                    "solver_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional: number of people who solved it.",
                        verbose_name="Number of solvers",
                    ),
                ),
                (
                    "ctf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ctf",
                        to="infosec.ctf",
                        verbose_name="CTF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Writeup",
                "verbose_name_plural": "Writeups",
            },
            bases=("blog.post",),
        ),
    ]
