# Generated by Django 5.2.7 on 2025-11-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("root", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="Title"),
                ),
                ("slug", models.SlugField(null=True, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CTF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("date_beginning", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
            ],
            options={
                "verbose_name": "CTF",
                "verbose_name_plural": "CTFs",
                "ordering": ["-date_beginning"],
            },
        ),
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Issuer",
                "verbose_name_plural": "Issuers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WriteupTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        help_text="the unique identifier for the CVE (e.g., CVE-2025-12345)",
                        max_length=20,
                        unique=True,
                        verbose_name="cve_id",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="a detailed description of the vulnerability",
                        verbose_name="description",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was published",
                        null=True,
                        verbose_name="published_date",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was last updated",
                        null=True,
                        verbose_name="last_modified_date",
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="the severity score of the vulnerability",
                        max_digits=3,
                        null=True,
                        verbose_name="cvss_score",
                    ),
                ),
                (
                    "vulnerable_product",
                    models.CharField(
                        blank=True,
                        help_text="the affected product(s)",
                        max_length=200,
                        null=True,
                        verbose_name="vulnerable_product",
                    ),
                ),
                (
                    "references_url",
                    models.URLField(
                        blank=True,
                        help_text="link to official references or advisories",
                        max_length=300,
                        null=True,
                        verbose_name="references_url",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cve",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField()),
                (
                    "certification_detail_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the official page of the certification",
                        null=True,
                        verbose_name="Certification URL",
                    ),
                ),
                (
                    "obtained_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the certification was obtained",
                        null=True,
                        verbose_name="Obtained Date",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification",
                        to="blog.article",
                        verbose_name="Related Article",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization or platform that issued the certification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="infosec.issuer",
                        verbose_name="Issuer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Writeup",
            fields=[
                (
                    "translatablemarkdownitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="root.translatablemarkdownitem",
                    ),
                ),
                (
                    "published_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published on"
                    ),
                ),
                (
                    "edited_on",
                    models.DateTimeField(auto_now=True, verbose_name="Edited on"),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("protected", "Protected"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=10,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Password"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("insane", "Insane"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Score or point value for this challenge.",
                        verbose_name="Points",
                    ),
                ),
                (
                    "solver_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional: number of people who solved it.",
                        verbose_name="Number of solvers",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="infosec.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "ctf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ctf",
                        to="infosec.ctf",
                        verbose_name="CTF",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="infosec.writeuptag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Writeup",
                "verbose_name_plural": "Writeups",
            },
            bases=("root.translatablemarkdownitem",),
        ),
    ]
