# Generated by Django 5.2.7 on 2025-11-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeup",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="writeups",
                to="infosec.category",
                verbose_name="Category",
            ),
        ),
    ]
