# Generated by Django 5.2.7 on 2025-11-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0002_categorytranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeup",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="writeup",
                to="infosec.category",
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="WriteupTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("it", "Italian"),
                        ],
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "translatable_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="infosec.writeup",
                        verbose_name="Translatable Writeup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Writeup Translation",
                "verbose_name_plural": "Writeup Translations",
                "abstract": False,
            },
        ),
    ]
