# Generated by Django 5.2.7 on 2025-11-02 23:08

from django.db import migrations, models

import root.utils


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0003_alter_writeup_category_writeuptranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_certifications,
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="writeup",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_posts,
                verbose_name="Picture",
            ),
        ),
    ]
