# Generated by Django 5.2.8 on 2026-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_credits",
            field=models.TextField(
                blank=True,
                default='Powered with ❤️ by <a href="https://github.com/DonAsako/eskoz">Eskoz</a>',
                null=True,
                verbose_name="Footer credits",
            ),
        ),
    ]
