# Generated by Django 5.2.8 on 2026-01-03 16:15

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesettings_footer_credits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="otp_is_active",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="otp_secret_key",
        ),
        migrations.CreateModel(
            name="User2FA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is 2FA active"),
                ),
                (
                    "secret_key",
                    models.CharField(
                        default=pyotp.random_base32,
                        max_length=64,
                        verbose_name="OTP secret key",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
