# Generated by Django 5.2.8 on 2026-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_userprofile_otp_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user2fa",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list, verbose_name="Backup codes"),
        ),
    ]
