# Generated by Django 5.2.8 on 2026-01-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user2fa_backup_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user2fa",
            name="backup_codes_viewed",
            field=models.BooleanField(default=False, verbose_name="Backup codes viewed"),
        ),
    ]
