# Generated by Django 6.0.4 on 2026-06-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user2fa_backup_codes_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True, verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=100, verbose_name="Role"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="Twitter / X"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
