# Generated by Django 6.0.4 on 2026-06-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_activate_members_view_to_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsettings",
            name="activate_members_page",
            field=models.BooleanField(default=False, verbose_name="Show team page"),
        ),
    ]
