# Generated by Django 6.0.4 on 2026-06-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pageview"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pageview",
            name="core_pagevi_content_00a2fe_idx",
        ),
        migrations.RemoveIndex(
            model_name="pageview",
            name="core_pagevi_created_d66d00_idx",
        ),
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
