# Generated by Django 6.0.4 on 2026-06-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_pageview_core_pagevi_content_00a2fe_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="show_transition",
        ),
    ]
