# Generated by Django 6.0.4 on 2026-06-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_sitesettings_show_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="check_for_updates",
            field=models.BooleanField(
                default=False,
                help_text="Periodically check GitHub for a newer Eskoz release and show a notice on the dashboard.",
                verbose_name="Check for updates",
            ),
        ),
    ]
