# Generated by Django 6.0.4 on 2026-06-29 17:30

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sitesettings_check_for_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablemarkdownitemimage",
            name="picture",
            field=models.ImageField(
                upload_to=apps.core.utils.upload_to_posts, verbose_name="Picture"
            ),
        ),
    ]
