# Generated by Django 6.0.4 on 2026-06-07 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_project_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_authored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Authors",
            ),
        ),
    ]
