# Generated by Django 6.0.4 on 2026-06-07 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_article_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["visibility", "-published_on"],
                name="blog_articl_visibil_2183fb_idx",
            ),
        ),
    ]
