# Generated by Django 5.2.4 on 2025-10-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField()),
                (
                    "certification_detail_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the official page of the certification",
                        null=True,
                        verbose_name="Certification URL",
                    ),
                ),
                (
                    "obtained_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the certification was obtained",
                        null=True,
                        verbose_name="Obtained Date",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pictures/",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="blog.article",
                        verbose_name="Related Article",
                    ),
                ),
            ],
        ),
    ]
