# Generated by Django 5.2.4 on 2025-10-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_certification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        help_text="the unique identifier for the CVE (e.g., CVE-2025-12345)",
                        max_length=20,
                        unique=True,
                        verbose_name="cve_id",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="a detailed description of the vulnerability",
                        verbose_name="description",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was published",
                        null=True,
                        verbose_name="published_date",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateField(
                        blank=True,
                        help_text="date when the CVE was last updated",
                        null=True,
                        verbose_name="last_modified_date",
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="the severity score of the vulnerability",
                        max_digits=3,
                        null=True,
                        verbose_name="cvss_score",
                    ),
                ),
                (
                    "vulnerable_product",
                    models.CharField(
                        blank=True,
                        help_text="the affected product(s)",
                        max_length=200,
                        null=True,
                        verbose_name="vulnerable_product",
                    ),
                ),
                (
                    "references_url",
                    models.URLField(
                        blank=True,
                        help_text="link to official references or advisories",
                        max_length=300,
                        null=True,
                        verbose_name="references_url",
                    ),
                ),
            ],
        ),
    ]
