# Generated by Django 5.2.7 on 2025-11-02 23:08

import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_posts,
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_projects,
                verbose_name="Picture",
            ),
        ),
    ]
