# Generated by Django 5.2.4 on 2025-10-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_certification_owner_cve_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Issuer",
                "verbose_name_plural": "Issuers",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="certification",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certification",
                to="blog.article",
                verbose_name="Related Article",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization or platform that issued the certification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certifications",
                to="blog.issuer",
                verbose_name="Issuer",
            ),
        ),
    ]
