# Generated by Django 5.2.4 on 2025-10-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_issuer_alter_certification_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="blog.article",
                verbose_name="Related Article",
            ),
        ),
    ]
