# Generated by Django 5.2.4 on 2025-10-28 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_project_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="maintenair",
            new_name="maintainer",
        ),
    ]
