# Generated by Django 5.2.4 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_rename_maintenair_project_maintainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_beginning",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
