# Generated by Django 5.2.1 on 2025-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
