# Generated by Django 5.2.4 on 2025-11-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_project_date_beginning_project_date_end"),
        ("infosec", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="article",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="issuer",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="writeup",
            name="ctf",
        ),
        migrations.RemoveField(
            model_name="cve",
            name="author",
        ),
        migrations.RemoveField(
            model_name="writeup",
            name="post_ptr",
        ),
        migrations.DeleteModel(
            name="Issuer",
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="CTF",
        ),
        migrations.DeleteModel(
            name="CVE",
        ),
        migrations.DeleteModel(
            name="Writeup",
        ),
    ]
