# Generated by Django 5.2.1 on 2025-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Description"
            ),
        ),
    ]
