# Generated by Django 5.2.1 on 2025-06-26 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_article_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "French"),
                            ("en", "English"),
                            ("it", "Italian"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="blog.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Translation",
                "verbose_name_plural": "Article Translations",
                "unique_together": {("article", "language")},
            },
        ),
    ]
