# Generated by Django 5.2.1 on 2025-06-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_migrate_article_to_translation"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="description"),
        migrations.RemoveField(model_name="article", name="content"),
    ]
