# Generated by Django 5.2.1 on 2025-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_article_title_content_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articletranslation",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French"), ("it", "Italian")],
                max_length=10,
            ),
        ),
    ]
