# Generated by Django 5.2.1 on 2025-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_category_slug_alter_category_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytranslation",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
