# Generated by Django 5.2.4 on 2025-10-26 19:48

from django.db import migrations


def link_articles_to_posts(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    Post = apps.get_model("blog", "Post")

    db_alias = schema_editor.connection.alias

    for article in Article.objects.using(db_alias).all():
        # Crée un Post correspondant à l'ancien Article
        post = Post.objects.using(db_alias).create(
            title=article.title,
            slug=article.slug,
            author=article.author,
            category=article.category,
            published_on=article.published_on,
            edited_on=article.edited_on,
            picture=article.picture,
            visibility=article.visibility,
            password=article.password,
        )

        # Copie les tags
        post.tags.set(article.tags.all())

        # Lier l’article à son post parent
        article.post_ptr = post
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_ctf_post_project_remove_article_author_and_more"),
    ]

    operations = [
        migrations.RunPython(
            link_articles_to_posts, reverse_code=migrations.RunPython.noop
        ),
    ]
