# Generated by Django 5.2.4 on 2025-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_project_alter_ctf_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
