# Generated by Django 6.0.4 on 2026-04-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeup",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Password"),
        ),
    ]
