# Generated by Django 6.0.4 on 2026-05-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0004_alter_categorytranslation_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cve",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
    ]
