# Generated by Django 6.0.4 on 2026-06-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0007_copy_writeup_author_to_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writeup",
            name="author",
        ),
    ]
