# Generated by Django 6.0.4 on 2026-06-07 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0008_remove_writeup_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cve",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="cves_authored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Authors",
            ),
        ),
    ]
