# Generated by Django 6.0.4 on 2026-06-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0010_copy_cve_author_to_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cve",
            name="author",
        ),
    ]
