# Generated by Django 6.0.4 on 2026-06-07 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0011_remove_cve_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cve",
            name="published_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="date when the CVE was published",
                null=True,
                verbose_name="published_date",
            ),
        ),
        migrations.AddIndex(
            model_name="writeup",
            index=models.Index(
                fields=["visibility", "-published_on"],
                name="infosec_wri_visibil_8b65d4_idx",
            ),
        ),
    ]
