# Generated by Django 6.0.4 on 2026-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosec", "0013_alter_ctf_date_beginning_alter_ctf_date_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Short code / acronym shown as the card title (e.g. CPTS, OSCP). Falls back to the name.",
                max_length=20,
                verbose_name="Code",
            ),
        ),
    ]
