# Generated by Django 6.0.4 on 2026-06-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_lesson_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="education.category",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                db_index=True,
                default="public",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
