# Generated by Django 5.2.7 on 2025-11-03 15:44

import django.db.models.deletion
import pyotp
import root.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=100, verbose_name="Site name"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_settings,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_settings,
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact mail"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "footer_credits",
                    models.CharField(
                        blank=True,
                        default='Powered with ❤️ by <a href="https://github.com/DonAsako/eskoz">Eskoz</a>',
                        max_length=250,
                        null=True,
                        verbose_name="Footer credits",
                    ),
                ),
                (
                    "under_maintenance",
                    models.BooleanField(
                        default=False, verbose_name="Under maintenance"
                    ),
                ),
                (
                    "show_transition",
                    models.BooleanField(
                        default=False, verbose_name="Show transition between page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Meta author"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta keywords"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google analytics id"
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Google tag manager id"
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Google site verification",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Open Graph title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_settings,
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary",
                        max_length=20,
                        verbose_name="Twitter card type",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Twitter title"
                    ),
                ),
                (
                    "twitter_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_settings,
                        verbose_name="Twitter image",
                    ),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_settings",
                        to="root.sitesettings",
                        verbose_name="SEO settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("referenced", "Referenced"),
                            ("index", "Index"),
                        ],
                        default="public",
                        max_length=10,
                        verbose_name="Visibility",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "site_settings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="root.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="TranslatableMarkdownItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "picture",
                    models.ImageField(
                        upload_to=root.utils.upload_to_settings, verbose_name="Picture"
                    ),
                ),
                (
                    "uploaded_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded on"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Markdown Image",
                "verbose_name_plural": "Markdown Images",
                "ordering": ["uploaded_on"],
            },
        ),
        migrations.CreateModel(
            name="UserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Title")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_users,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=root.utils.upload_to_users,
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "otp_is_active",
                    models.BooleanField(default=False, verbose_name="Is 2FA active"),
                ),
                (
                    "otp_secret_key",
                    models.CharField(
                        default=pyotp.random_base32,
                        max_length=64,
                        verbose_name="OTP secret key",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activate_certifications_page",
                    models.BooleanField(
                        default=True, verbose_name="Show certification page"
                    ),
                ),
                (
                    "activate_projects_page",
                    models.BooleanField(default=True, verbose_name="Show project page"),
                ),
                (
                    "activate_articles_page",
                    models.BooleanField(default=True, verbose_name="Show article page"),
                ),
                (
                    "activate_cves_page",
                    models.BooleanField(default=True, verbose_name="Show cve page"),
                ),
                (
                    "activate_writeups_page",
                    models.BooleanField(default=True, verbose_name="Show writeup page"),
                ),
                (
                    "activate_members_page",
                    models.BooleanField(default=True, verbose_name="Show member page"),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_page_settings",
                        to="root.sitesettings",
                        verbose_name="View page settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WellKnownFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "site_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_knowns",
                        to="root.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "WellKnown File",
                "verbose_name_plural": "WellKnown Files",
            },
        ),
    ]
