# Generated by Django 5.2.1 on 2025-05-18 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=100, verbose_name="Site name"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact mail"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Meta author"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta keywords"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google analytics id"
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Google tag manager id"
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Google site verification",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Open Graph title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Open Graph description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="SEO/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary",
                        max_length=20,
                        verbose_name="Twitter card type",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Twitter title"
                    ),
                ),
                (
                    "twitter_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="SEO/",
                        verbose_name="Twitter image",
                    ),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_settings",
                        to="root.sitesettings",
                        verbose_name="SEO settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Primary color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Secondary color"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Background color"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Text color"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Font family"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "site_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="root.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.CreateModel(
            name="UserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Title")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="icons/", verbose_name="Icon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WellKnownFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "site_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_knowns",
                        to="root.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "WellKnown File",
                "verbose_name_plural": "WellKnown Files",
            },
        ),
    ]
