# Generated by Django 5.2.7 on 2025-11-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activate_members_view",
                    models.BooleanField(
                        default=False, verbose_name="Show members page"
                    ),
                ),
                (
                    "activate_projects_page",
                    models.BooleanField(default=True, verbose_name="Show project page"),
                ),
                (
                    "activate_articles_page",
                    models.BooleanField(default=True, verbose_name="Show article page"),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to="root.sitesettings",
                        verbose_name="Blog settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activate_courses_page",
                    models.BooleanField(
                        default=False, verbose_name="Show courses page"
                    ),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="root.sitesettings",
                        verbose_name="Education settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfosecSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activate_certifications_page",
                    models.BooleanField(
                        default=True, verbose_name="Show certification page"
                    ),
                ),
                (
                    "activate_cves_page",
                    models.BooleanField(default=True, verbose_name="Show cve page"),
                ),
                (
                    "activate_writeups_page",
                    models.BooleanField(default=True, verbose_name="Show writeup page"),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infosec",
                        to="root.sitesettings",
                        verbose_name="Infosec settings",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ViewPageSettings",
        ),
    ]
