# Generated by Django 5.2.7 on 2025-11-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="site_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="root.sitesettings",
            ),
        ),
    ]
