# Generated by Django 5.2.1 on 2025-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="under_maintenance",
            field=models.BooleanField(default=False, verbose_name="Under maintenance"),
        ),
    ]
