# Generated by Django 5.2.7 on 2025-11-02 23:08

import django.db.models.deletion
import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("root", "0002_page_site_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seosettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_settings,
                verbose_name="Open Graph image",
            ),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="twitter_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_settings,
                verbose_name="Twitter image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_settings,
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_settings,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="userlink",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_users,
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=root.utils.upload_to_users,
                verbose_name="Avatar",
            ),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "picture",
                    models.ImageField(
                        upload_to=root.utils.upload_to_settings, verbose_name="Picture"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "uploaded_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded on"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Image",
                "verbose_name_plural": "Post Images",
                "ordering": ["uploaded_on"],
            },
        ),
    ]
