# Generated by Django 5.2.7 on 2025-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_blogsettings_educationsettings_infosecsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Activate Blog Module"
            ),
        ),
        migrations.AddField(
            model_name="educationsettings",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Activate Education Module"
            ),
        ),
        migrations.AddField(
            model_name="infosecsettings",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Activate Infosec Module"
            ),
        ),
    ]
