# Generated by Django 5.2.1 on 2025-05-18 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0002_sitesettings_under_maintenance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="font_family",
        ),
    ]
