# Generated by Django 5.2.1 on 2025-05-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0004_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="page",
            name="site_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page",
                to="root.sitesettings",
            ),
        ),
    ]
