# Generated by Django 5.2.1 on 2025-05-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0005_page_slug_alter_page_site_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="Slug"),
        ),
    ]
