# Generated by Django 5.2.1 on 2025-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0007_alter_page_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_credits",
            field=models.CharField(
                default='Powered with ❤️ by <a href="https://github.com/DonAsako/eskoz">Eskoz</a>',
                max_length=250,
                verbose_name="Footer credits",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
