# Generated by Django 5.2.1 on 2025-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0008_sitesettings_footer_credits_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("referenced", "Referenced"),
                    ("index", "Index"),
                ],
                default="public",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_credits",
            field=models.CharField(
                blank=True,
                default='Powered with ❤️ by <a href="https://github.com/DonAsako/eskoz">Eskoz</a>',
                max_length=250,
                null=True,
                verbose_name="Footer credits",
            ),
        ),
    ]
