# Generated by Django 5.2.1 on 2025-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0009_alter_page_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="show_transition",
            field=models.BooleanField(
                default=False, verbose_name="Show transition between page"
            ),
        ),
    ]
