# Generated by Django 5.2.1 on 2025-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0011_theme_theme_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="show_transition",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_transition",
            field=models.BooleanField(
                default=False, verbose_name="Show transition between page"
            ),
        ),
    ]
