# Generated by Django 5.2.1 on 2025-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0012_remove_theme_show_transition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="text_color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="theme",
            name="path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="theme",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="theme_previews/"),
        ),
        migrations.AddField(
            model_name="theme",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
    ]
