# Generated by Django 5.2.1 on 2025-07-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0013_remove_theme_background_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="theme_type",
        ),
    ]
