# Generated by Django 5.2.4 on 2025-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0015_delete_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="secret_key",
            field=models.CharField(blank=True, null=True),
        ),
    ]
