# Generated by Django 5.2.4 on 2025-10-22 17:48

import pyotp
from django.db import migrations, models


def generate_otp_keys(apps, schema_editor):
    UserProfile = apps.get_model("root", "UserProfile")
    for profile in UserProfile.objects.filter(otp_secret_key__isnull=True):
        profile.otp_secret_key = pyotp.random_base32()
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0016_userprofile_secret_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_is_active",
            field=models.BooleanField(default=False, verbose_name="Is OTP active"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_secret_key",
            field=models.CharField(
                default=pyotp.random_base32,
                max_length=64,
                verbose_name="OTP secret key",
            ),
        ),
        migrations.RunPython(generate_otp_keys),
    ]
