# Generated by Django 5.2.4 on 2025-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0017_remove_userprofile_secret_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="otp_is_active",
            field=models.BooleanField(default=False, verbose_name="Is 2FA active"),
        ),
    ]
