# Generated by Django 5.2.4 on 2025-11-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0018_alter_userprofile_otp_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activate_certifications_page",
                    models.BooleanField(
                        default=True, verbose_name="Show certification page"
                    ),
                ),
                (
                    "activate_projects_page",
                    models.BooleanField(default=True, verbose_name="Show project page"),
                ),
                (
                    "activate_articles_page",
                    models.BooleanField(default=True, verbose_name="Show article page"),
                ),
                (
                    "activate_cves_page",
                    models.BooleanField(default=True, verbose_name="Show cve page"),
                ),
                (
                    "activate_writeups_page",
                    models.BooleanField(default=True, verbose_name="Show writeup page"),
                ),
                (
                    "activate_members_page",
                    models.BooleanField(default=True, verbose_name="Show member page"),
                ),
                (
                    "site_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_page_settings",
                        to="root.sitesettings",
                        verbose_name="View page settings",
                    ),
                ),
            ],
        ),
    ]
