# Generated by Django 6.0.4 on 2026-06-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("visitor_hash", models.CharField(db_index=True, max_length=64)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page view",
                "verbose_name_plural": "Page views",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="analytics_p_content_e973c6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_4c2b45_idx"
                    ),
                ],
            },
        ),
    ]
