# Generated by Django 6.0.4 on 2026-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="pageview",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="pageview",
            name="utm_source",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
